-- DATA BASE SCHEMA  -- 

CREATE TABLE AUTHOR (
  ID INT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE BOOK (
  ID INT PRIMARY KEY,
  TITLE VARCHAR(50) NOT NULL UNIQUE,
  AUTHOR_ID INT NOT NULL,
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);

